-- FROM
SELECT *
FROM EMPLOYEES;


-- SELECT
-- 	Math operations +,-,*,/, MOD, ROUND, CEIL, FLOOR
-- 	String operations ||,UPPER,LOWER,SUBSTR,LENGTH
-- 	Alias
-- 	NVL
SELECT FIRST_NAME, LAST_NAME
FROM EMPLOYEES;

SELECT 1+1, 2*3, 1/4, MOD(10, 3), ROUND(1.6), CEIL(1.6), FLOOR(1.6)
FROM DUAL;  

SELECT SALARY * 0.1 AS BONUS
FROM EMPLOYEES;

SELECT FIRST_NAME || ' ' || LAST_NAME AS FULL_NAME
FROM EMPLOYEES;

SELECT LAST_NAME || ', ' || FIRST_NAME AS FULL_NAME
FROM EMPLOYEES;


SELECT SUBSTR(FIRST_NAME,1,1) || '. ' || LAST_NAME AS FULL_NAME
FROM EMPLOYEES;


SELECT FIRST_NAME || ' ' || LAST_NAME AS "Full Name"
FROM EMPLOYEES;


SELECT LOWER(FIRST_NAME), UPPER(LAST_NAME), INITCAP(EMAIL)
FROM EMPLOYEES;


SELECT 
	SALARY * NVL(COMMISSION_PCT,0) AS COMMISSION, 
	SALARY + SALARY * NVL(COMMISSION_PCT,0) AS TOTAL_PAY
FROM EMPLOYEES;


-- WHERE
-- 	AND
-- 	OR
-- 	NOT
-- 	NULL
-- 	IN
-- 	BETWEEN
-- 	LIKE
SELECT *
FROM EMPLOYEES
WHERE SALARY > 10000 AND SALARY < 15000;

SELECT *
FROM EMPLOYEES
WHERE SALARY <= 10000 OR SALARY >= 15000;

SELECT *
FROM EMPLOYEES
WHERE NOT (SALARY > 10000 AND SALARY < 15000);

SELECT *
FROM EMPLOYEES
WHERE MANAGER_ID = 100;

SELECT *
FROM EMPLOYEES
WHERE MANAGER_ID <> 100;

SELECT *
FROM EMPLOYEES
WHERE NOT (MANAGER_ID = NULL);

SELECT *
FROM EMPLOYEES
WHERE MANAGER_ID IS NULL;

SELECT *
FROM EMPLOYEES
WHERE MANAGER_ID IS NOT NULL;

SELECT *
FROM EMPLOYEES
WHERE MANAGER_ID = 100 OR MANAGER_ID = 102 OR MANAGER_ID = 121 OR MANAGER_ID = 124;

SELECT *
FROM EMPLOYEES
WHERE MANAGER_ID IN (100, 102, 121, 124) OR MANAGER_ID IS NULL;

SELECT *
FROM EMPLOYEES
WHERE MANAGER_ID NOT IN (100, 102, 121, 124);

SELECT *
FROM EMPLOYEES
WHERE SALARY >= 10000 AND SALARY <= 15000;

SELECT *
FROM EMPLOYEES
WHERE SALARY BETWEEN 10000 AND 15000;

SELECT *
FROM EMPLOYEES
WHERE SUBSTR(FIRST_NAME, 1, 1) = 'A';

SELECT *
FROM EMPLOYEES
WHERE SUBSTR(FIRST_NAME, LENGTH(FIRST_NAME), 2) = 'a';

SELECT *
FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'A%';

SELECT *
FROM EMPLOYEES
WHERE FIRST_NAME LIKE '%a';

SELECT *
FROM EMPLOYEES
WHERE LOWER(FIRST_NAME) LIKE '%a%';

SELECT *
FROM EMPLOYEES
WHERE FIRST_NAME LIKE '%i%a%' OR FIRST_NAME LIKE '%a%i%';

SELECT *
FROM EMPLOYEES
WHERE FIRST_NAME LIKE '%____a';


-- ORDER BY
SELECT *
FROM EMPLOYEES
ORDER BY FIRST_NAME ASC;

SELECT *
FROM EMPLOYEES
ORDER BY SALARY DESC, FIRST_NAME;



--exercise

SELECT HIRE_DATE,(FIRST_NAME ||' '|| LAST_NAME) AS FULLNAME
FROM EMPLOYEES
WHERE HIRE_DATE <= '01-JAN-2006';


SELECT FIRST_NAME, LAST_NAME, HIRE_DATE 
FROM EMPLOYEES 
WHERE TO_CHAR(HIRE_DATE, 'YYYY') >= '2003'
ORDER BY HIRE_DATE;

SELECT FIRST_NAME, LAST_NAME, HIRE_DATE 
FROM EMPLOYEES 
WHERE TO_CHAR(HIRE_DATE, 'MON') = 'JAN'
ORDER BY HIRE_DATE;


SELECT LAST_NAME
FROM EMPLOYEES
WHERE LOWER(LAST_NAME) not LIKE '%s%';


SELECT CONCAT(FIRST_NAME, LAST_NAME) AS FULLNAME
FROM EMPLOYEES;

SELECT TO_CHAR(HIRE_DATE, 'YYYY') YEAR, COUNT(*) TOTAL
FROM EMPLOYEES 
GROUP BY TO_CHAR(HIRE_DATE, 'YYYY') 
ORDER BY YEAR ASC ;


SELECT SUBSTR(FIRST_NAME, 1, 1) AS LL , COUNT(*)
FROM EMPLOYEES
GROUP BY SUBSTR(FIRST_NAME, 1, 1) 
ORDER BY SUBSTR(FIRST_NAME, 1, 1) ASC;

SELECT TO_CHAR(HIRE_DATE,'YYYY') AS YEAR, JOB_ID, COUNT(*) AS "TOTAL EMP"
FROM EMPLOYEES
GROUP BY TO_CHAR(HIRE_DATE,'YYYY') , JOB_ID
ORDER BY TO_CHAR(HIRE_DATE,'YYYY') , JOB_ID ASC;


SELECT SUBSTR(FIRST_NAME, LENGTH(FIRST_NAME)-3, 3)
FROM EMPLOYEES;


SELECT LAST_NAME, TO_DATE(SYSDATE) - HIRE_DATE AS "DAYS EMPLOYED"
FROM EMPLOYEES;


SELECT (SYSDATE - HIRE_DATE)/7 "WEEKS EMPLOYED"
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 80 ;

SELECT ROUND(SYSDATE) - TO_DATE('21-02-2002','DD-MM-YYYY') AS "DAYS"
FROM DUAL;







