SELECT E.FIRST_NAME || ' '|| E.LAST_NAME
FROM EMPLOYEES E;

SELECT E.FIRST_NAME , E.LAST_NAME , D.DEPARTMENT_NAME
FROM EMPLOYEES E JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

SELECT *
FROM REGIONS;

SELECT *
FROM COUNTRIES;

SELECT *
FROM COUNTRIES,REGIONS; --CROSS PRODUCT ER MOTO
-- FROM COUNTRIES CROSS JOIN REGIONS;

SELECT *
FROM COUNTRIES C,REGIONS R
WHERE C.REGION_ID=R.REGION_ID -- CROSS HOBE THEN FILTER
ORDER BY COUNTRY_ID;



SELECT *
FROM COUNTRIES C CROSS JOIN REGIONS R ON C.REGION_ID=R.REGION_ID -- USING(REGION_ID)
-- using er subidha holo duita coln ar thaktasena ...
ORDER BY COUNTRY_ID;

-- NATURAL JOIN

SELECT *
FROM EMPLOYEES E LEFT JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;
--LEFT TABLE R SHB ROW JATE THAKE NULL ID THAKLEO
--FROM EMPLOYEES E FULL JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;


SELECT *
FROM EMPLOYEES E FULL JOIN DEPARTMENTS D USING (DEPARTMENT_ID)
ORDER BY DEPARTMENT_ID;


--for each emplpyee, print the no of other EMPLOYEES he MANAGER_ID
SELECT M.EMPLOYEE_ID, M.FIRST_NAME, M.LAST_NAME, COUNT(E.MANAGER_ID), COUNT(*)
FROM EMPLOYEES M LEFT JOIN EMPLOYEES E ON M.EMPLOYEE_ID= E.MANAGER_ID -- E HOLO MANAGER KRE
GROUP BY M.EMPLOYEE_ID, M.FIRST_NAME, M.LAST_NAME
ORDER BY M.EMPLOYEE_ID;

SELECT *
FROM EMPLOYEES M LEFT JOIN EMPLOYEES E ON M.EMPLOYEE_ID= E.MANAGER_ID -- E HOLO MANAGER KRE
ORDER BY M.EMPLOYEE_ID;

--for each department, print the number of employees working in that dept

SELECT D.DEPARTMENT_ID, COUNT(E.EMPLOYEE_ID) AS N_EMPLOYEES
FROM EMPLOYEES E RIGHT JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_ID;
































