-- subquery




--PROTI DEPT R MAX SALARY KOTO
SELECT DEPARTMENT_ID, MAX(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

SELECT D.*,(		--SELECT R POR * DILE AR KISU LIKHA JABENA NAILE ERR
	SELECT MAX(SALARY)
	FROM EMPLOYEES
	WHERE DEPARTMENT_ID= D.DEPARTMENT_ID
)	
AS MAX_EM_SALARY
FROM DEPARTMENTS D;



--JARA AVG R CHEYE BESHI SALARY PAE  AMOONG ALL EMPLOYEES
SELECT *
FROM EMPLOYEES
WHERE SALARY>(
	SELECT AVG(SALARY)
	FROM EMPLOYEES
);
ORDER BY DEPARTMENT_ID;
--JARA AVG R CHEYE BESHI SALARY PAE  AMOONG ALL EMPLOYEES(ONLY AMONG HIS DEPT BUDDIES)
SELECT *
FROM EMPLOYEES E
WHERE SALARY>(
	SELECT AVG(SALARY)
	FROM EMPLOYEES
	WHERE DEPARTMENT_ID=E.DEPARTMENT_ID
)
ORDER BY DEPARTMENT_ID;

--PRINT ALL INFO OF EMPLOYEES THAT RECEIVE SALARY THAT IS EQUAL TO MAX SALARY OF HIS DEPARTMENT
SELECT *
FROM EMPLOYEES E
WHERE SALARY=(
	SELECT MAX(SALARY)
	FROM EMPLOYEES
	WHERE DEPARTMENT_ID=E.DEPARTMENT_ID
)
ORDER BY DEPARTMENT_ID;

--PROTI DEPT E KE MAX SALARY PAE TAR INFO
SELECT *
FROM EMPLOYEES E RIGHT JOIN DEPARTMENTS D ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
WHERE SALARY=(
	SELECT MAX(SALARY)
	FROM EMPLOYEES
	WHERE DEPARTMENT_ID=E.DEPARTMENT_ID
)
ORDER BY E.DEPARTMENT_ID;


--print info of the employee that gets salary higher than all employ in other dept
SELECT *
FROM EMPLOYEES E RIGHT JOIN DEPARTMENTS D ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
WHERE E.SALARY>ALL(
	SELECT SALARY
	FROM EMPLOYEES
	WHERE DEPARTMENT_ID=E.DEPARTMENT_ID AND EMPLOYEE_ID = D.DEPARTMENT_ID
)
OR E.SALARY IS NULL
ORDER BY D.DEPARTMENT_ID;



SELECT *
FROM EMPLOYEES E
WHERE EXISTS(
	SELECT SALARY 
	FROM EMPLOYEES
	WHERE E. SALARY>SALARY AND EMPLOYEE_ID = E.MANAGER_ID
);

-- FROM QUERY
SELECT *
FROM DEPARTMENTS D JOIN(
	SELECT E.DEPARTMENT_ID, COUNT(*) AS N_EM  -- COLUMN NAAM USE 'AS' DONOT USE FOR TABLE
FROM EMPLOYEES E
GROUP BY E.DEPARTMENT_ID
)N ON D.DEPARTMENT_ID= N.DEPARTMENT_ID


=--WITH
WITH N AS(
	SELECT E.DEPARTMENT_ID, COUNT(*) AS N_EM  -- COLUMN NAAM USE 'AS' DONOT USE FOR TABLE
	FROM EMPLOYEES E
	GROUP BY E.DEPARTMENT_ID
)
SELECT *
FROM DEPARTMENTS D JOIN N ON D.DEPARTMENT_ID= N.DEPARTMENT_ID;



WITH N AS(
	SELECT E.DEPARTMENT_ID, COUNT(*) AS N_EM  -- COLUMN NAAM USE 'AS' DONOT USE FOR TABLE
	FROM EMPLOYEES E
	GROUP BY E.DEPARTMENT_ID
),
	T AS(
	SELECT E.DEPARTMENT_ID, MAX(SALARY) AS SALARY_MAX
	FROM EMPLOYEES E
	GROUP BY E.DEPARTMENT_ID
SELECT *
FROM DEPARTMENTS D JOIN N ON D.DEPARTMENT_ID= N.DEPARTMENT_ID 
JOIN T ON D.DEPARTMENT_ID= T.DEPARTMENT_ID;















