-- SELECT
-- 	DISTINCT
SELECT DISTINCT MANAGER_ID
FROM EMPLOYEES;

SELECT DISTINCT MANAGER_ID, JOB_ID
FROM EMPLOYEES
ORDER BY MANAGER_ID, JOB_ID;

-- 	CASE
-- GRADE A: SALARY < 10000
-- GRADE B: SALARY >= 10000 & SALARY < 20000
-- GRADE C: SALARY >= 20000
SELECT 
	EMPLOYEE_ID,
	CASE
		WHEN SALARY < 10000 THEN 'A'
		WHEN SALARY < 20000 THEN 'B'
		ELSE 'C'
	END 
	AS GRADE
FROM EMPLOYEES;

-- 	Aggregation functions COUNT,SUM,MAX,MIN,AVG
SELECT COUNT(*)
FROM EMPLOYEES;

SELECT COUNT(MANAGER_ID), COUNT(DISTINCT MANAGER_ID), COUNT(DISTINCT SALARY)
FROM EMPLOYEES;

SELECT SUM(SALARY), MAX(SALARY), MIN(SALARY), ROUND(AVG(SALARY),2), MAX(SALARY) + MIN(SALARY)
FROM EMPLOYEES;

SELECT
	SUM(
		CASE
			WHEN JOB_ID = 'FI_ACCOUNT' THEN SALARY
			ELSE 0
		END
	)
	AS Sum1,
	SUM(
		CASE
			WHEN JOB_ID = 'ST_MAN' THEN SALARY
			ELSE 0
		END
	)
FROM EMPLOYEES;

-- GROUP BY
SELECT JOB_ID, SUM(SALARY)
FROM EMPLOYEES
GROUP BY JOB_ID;

SELECT JOB_ID, SUM(SALARY)
FROM EMPLOYEES
WHERE JOB_ID IN ('FI_ACCOUNT', 'ST_MAN')
GROUP BY JOB_ID;

SELECT MANAGER_ID, JOB_ID, COUNT(*)
FROM EMPLOYEES
GROUP BY MANAGER_ID, JOB_ID
ORDER BY MANAGER_ID, JOB_ID;


-- HAVING
SELECT JOB_ID, SUM(SALARY)
FROM EMPLOYEES
GROUP BY JOB_ID
HAVING JOB_ID IN ('FI_ACCOUNT', 'ST_MAN');


SELECT JOB_ID, COUNT(*) AS N_EMPLOYEE, SUM(SALARY) AS TOTAL_SALARY
FROM EMPLOYEES
WHERE SALARY > 10000
GROUP BY JOB_ID
HAVING COUNT(*) > 1
ORDER BY N_EMPLOYEE DESC, TOTAL_SALARY;


SELECT JOB_ID, COUNT(*) AS N_EMPLOYEE, SUM(SALARY) AS TOTAL_SALARY -- 5
FROM EMPLOYEES -- 1
WHERE SALARY > 10000 -- 2
GROUP BY JOB_ID -- 3
HAVING COUNT(*) > 1 -- 4
ORDER BY N_EMPLOYEE DESC, TOTAL_SALARY -- 6
;

SELECT E.DEPARTMENT_ID, COUNT(*)
FROM EMPLOYEES E
GROUP BY E.DEPARTMENT_ID; -- nullKEO dept id KRE gese



SELECT JOB_ID, AVG(SALARY) 
FROM EMPLOYEES
WHERE SALARY<=5000
GROUP BY JOB_ID
HAVING AVG(SALARY)<=5000
ORDER BY AVG(SALARY) DESC ;
